export {
	projects,
	artifacts,
	artifactVersions,
	projectKindEnum,
	artifactContentTypeEnum,
	type ProjectRow,
	type ArtifactRow,
	type ArtifactVersionRow,
	type ProjectKind,
	type ArtifactContentType,
} from './projects.schema'
export {
	slugify,
	createProject,
	listProjects,
	getProjectById,
	getProjectBySlug,
	updateProject,
	deleteProject,
	createArtifact,
	editArtifact,
	getArtifactById,
	listArtifactsForProject,
	getVersionHistory,
	getVersion,
	rollbackArtifact,
	softDeleteArtifact,
	type CreateProjectInput,
	type CreateArtifactInput,
	type EditArtifactInput,
	type ArtifactWithCurrent,
} from './projects.server'
export {
	listProjectsQuery,
	getProjectByIdQuery,
	createProjectCommand,
	updateProjectCommand,
	deleteProjectCommand,
	getArtifactQuery,
	getVersionQuery,
	createArtifactCommand,
	editArtifactCommand,
	rollbackArtifactCommand,
	softDeleteArtifactCommand,
} from './projects.remote'
